VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "fileClass"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
   Public this_filename As Variant
   Public mypath As Variant
   Public mybook As Variant
   Public mybook_month As Variant
   Public mmfn As Variant
   Public fn As Variant
   Public next_mybook As Variant
   Public bool_filename As Variant
   Public checkFilename  As Variant



