VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "dateClass"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
   Public date_now As Variant
   Public date_next As Variant
   Public date_last As Variant
   Public date_after_next As Variant
   Public H_AL_nowMonth As Variant
   Public H_AL_nextMonth As Variant
   Public H_AL_Month_after_next As Variant
   Public G_now_date As Variant
   Public G_last_date As Variant
   Public G_next_date As Variant
   Public kowake_now_date As Variant
   Public kowake_last_date As Variant
   Public kowake_next_date As Variant
